plugin-enabled: true

head-texture: "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvMTAzNWM1MjgwMzZiMzg0YzUzYzljOGExYTEyNTY4NWUxNmJmYjM2OWMxOTdjYzlmMDNkZmEzYjgzNWIxYWE1NSJ9fX0="

chances:
  normal: 50
  broken: 35
  enchanted: 15

messages:
  normal: "§eYou crafted a normal item."
  broken: "§c§lOOF §cYou crafted a broken item."
  enchanted: "§2§lWOW! §2You crafted an enchanted item."

disable-for:
  armor: false
  tools: false
  crossbows: false # Enable this if below 1.14
  bows: false
  shields: false
  mace: true  # Enable this if below 1.21
  wolf_armor: true  # Enable this if below 1.21
