name: RealisticCrafting
version: '1.0-SNAPSHOT'
main: me.heroicstudios.realisticcrafting.RealisticCrafting
api-version: '1.18'
author: HeroicStudios
description: A plugin that adds realistic crafting outcomes with randomized results.

commands:
  rcreload:
    description: Reloads the RealisticCrafting configuration.
    usage: /<command>
    permission: realisticcrafting.reload
    permission-message: You do not have permission to execute this command.

permissions:
  realisticcrafting.reload:
    description: Allows the player to reload the plugin's configuration.
    default: op